---
abstract: 'A simple interface to the PC-Axis file format'
author:
  - "Fiachra O'Donoghue <fod@cpan.org>"
build_requires:
  JSON: 0
  POSIX: 0
  Test::More: 0
  feature: 0
  match::smart: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-PcAxis
requires:
  Carp: 0
  List::AllUtils: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Types::Path::Class: 0
  Text::CSV: 0
  autodie: 0
  namespace::autoclean: 0
  perl: 5.010
version: 0.0.7
x_BuiltWith:
  modules:
    Carp: 1.29
    ExtUtils::MakeMaker: 6.66
    JSON: 2.53
    List::AllUtils: 0.07
    Moose: 2.1202
    Moose::Util::TypeConstraints: 2.1202
    MooseX::Types::Path::Class: 0.05
    POSIX: 1.32
    Test::More: 1.001002
    Test::Pod: 1.45
    Text::CSV: 1.21
    autodie: 2.13
    feature: 1.32
    match::smart: 0.006
    namespace::autoclean: 0.13
    perl: 'NA(skipped: perl)'
    strict: 1.07
    warnings: 1.18
  perl:
    original: v5.18.2
    qv: 1
    version:
      - 5
      - 18
      - 2
  platform: linux
